"""故障案例 Mock 数据"""

FAULT_CASES: list[dict] = [
    {
        "case_id": "FC-001",
        "title": "220kV变压器绕组过热故障",
        "equipment_type": "transformer",
        "equipment_id": "TR-002",
        "fault_type": "过热故障",
        "fault_subtype": "绕组高温过热",
        "severity": "严重",
        "occurrence_date": "2024-08-15",
        "description": "2号主变油温持续升高，DGA检测发现甲烷和乙烯含量显著增长，三比值法诊断为高温过热故障。经吊芯检查发现A相绕组匝间短路。",
        "symptoms": [
            "油温持续升高，超过75°C注意值",
            "DGA数据：CH4=55ppm，C2H4=70ppm，C2H2=8ppm",
            "总烃含量超过150ppm注意值",
            "铁芯接地电流异常增大",
        ],
        "root_cause": "A相高压绕组第15-18饼匝间绝缘劣化导致短路，产生局部高温热点",
        "evidence_chain": [
            {"step": 1, "evidence": "油温趋势分析显示30天内温度上升8°C", "confidence": 0.95},
            {"step": 2, "evidence": "DGA三比值法判定为高温过热（T2型）", "confidence": 0.92},
            {"step": 3, "evidence": "铁芯接地电流从正常0.1A升至2.5A", "confidence": 0.88},
            {"step": 4, "evidence": "绕组直流电阻不平衡率超标（A相偏差2.3%）", "confidence": 0.96},
            {"step": 5, "evidence": "吊芯检查确认A相绕组匝间短路", "confidence": 1.0},
        ],
        "corrective_actions": [
            "立即降低负荷至额定60%",
            "安排停电检修，进行绕组更换",
            "更换绝缘油并进行真空注油",
            "修复后进行短路阻抗试验和局放试验",
        ],
        "prevention_measures": [
            "缩短DGA检测周期至每月1次",
            "加装绕组温度在线监测装置",
            "同批次设备开展绝缘电阻普查",
        ],
        "resolution_date": "2024-09-20",
        "cost": 285000,
        "downtime_hours": 864,
    },
    {
        "case_id": "FC-002",
        "title": "110kV断路器SF6气体泄漏",
        "equipment_type": "breaker",
        "equipment_id": "CB-003",
        "fault_type": "气体泄漏",
        "fault_subtype": "SF6气体压力下降",
        "severity": "一般",
        "occurrence_date": "2024-11-03",
        "description": "110kV余北线断路器SF6气体压力持续下降，从额定0.6MPa降至0.52MPa，触发低气压告警。经检测发现灭弧室密封件老化导致气体泄漏。",
        "symptoms": [
            "SF6气压从0.6MPa降至0.52MPa",
            "月泄漏率约2.5%，超过标准1%/年",
            "红外检漏发现灭弧室法兰结合面有泄漏",
        ],
        "root_cause": "灭弧室法兰O型密封圈老化龟裂，运行年限达12年超过建议更换周期",
        "evidence_chain": [
            {"step": 1, "evidence": "SF6压力趋势分析显示持续下降", "confidence": 0.98},
            {"step": 2, "evidence": "红外检漏仪定位泄漏点在法兰结合面", "confidence": 0.93},
            {"step": 3, "evidence": "密封圈弹性测试硬度超标（邵氏A 85→92）", "confidence": 0.90},
            {"step": 4, "evidence": "运行年限12年超过厂家建议10年更换周期", "confidence": 0.85},
        ],
        "corrective_actions": [
            "补充SF6气体至额定压力",
            "安排停电更换全部密封件",
            "更换吸附剂和干燥剂",
            "进行气密性试验和微水含量检测",
        ],
        "prevention_measures": [
            "建立SF6压力在线监测系统",
            "同批次断路器开展密封件状态普查",
            "制定密封件定期更换计划（8年周期）",
        ],
        "resolution_date": "2024-11-20",
        "cost": 45000,
        "downtime_hours": 48,
    },
    {
        "case_id": "FC-003",
        "title": "220kV GIS局部放电异常",
        "equipment_type": "gis",
        "equipment_id": "GIS-002",
        "fault_type": "绝缘缺陷",
        "fault_subtype": "自由颗粒放电",
        "severity": "严重",
        "occurrence_date": "2024-06-22",
        "description": "110kV GIS特高频局部放电检测发现异常信号，PRPD谱图特征显示为自由金属颗粒放电模式。开盖检查发现母线筒内有金属微粒。",
        "symptoms": [
            "UHF局放信号幅值达到350mV",
            "PRPD谱图呈现典型颗粒放电特征（全相位分布）",
            "超声波检测在母线筒位置检测到异常信号",
            "信号幅值随时间逐渐增大",
        ],
        "root_cause": "隔离开关操作产生的金属微粒残留，在电场作用下形成自由颗粒放电",
        "evidence_chain": [
            {"step": 1, "evidence": "UHF检测发现持续局放信号，幅值350mV", "confidence": 0.97},
            {"step": 2, "evidence": "PRPD谱图分析判定为自由颗粒放电模式", "confidence": 0.91},
            {"step": 3, "evidence": "超声波辅助定位在母线筒第三气室", "confidence": 0.88},
            {"step": 4, "evidence": "开盖检查发现5颗直径0.5-2mm金属微粒", "confidence": 1.0},
        ],
        "corrective_actions": [
            "停电处理，开盖清理金属微粒",
            "更换受损绝缘子表面",
            "进行252kV交流耐压试验",
            "重新充气后进行局放复测",
        ],
        "prevention_measures": [
            "加装UHF在线监测装置",
            "隔离开关操作后增加局放检测频次",
            "建立PRPD谱图特征库用于模式识别",
        ],
        "resolution_date": "2024-07-15",
        "cost": 180000,
        "downtime_hours": 168,
    },
    {
        "case_id": "FC-004",
        "title": "220kV变压器套管介损超标",
        "equipment_type": "transformer",
        "equipment_id": "TR-004",
        "fault_type": "绝缘劣化",
        "fault_subtype": "套管介损超标",
        "severity": "一般",
        "occurrence_date": "2024-04-10",
        "description": "预防性试验发现3号主变A相高压套管介损值达到1.2%，超过规程注意值0.8%。油色谱分析显示套管油中氢气含量异常。",
        "symptoms": [
            "A相高压套管介损值1.2%（注意值0.8%）",
            "套管油中H2含量达到85ppm",
            "套管电容量较上次试验增长3.5%",
        ],
        "root_cause": "套管内部受潮，绝缘纸含水量超标导致介损升高",
        "evidence_chain": [
            {"step": 1, "evidence": "介损值1.2%超过0.8%注意值", "confidence": 0.95},
            {"step": 2, "evidence": "套管油DGA显示H2异常（85ppm）", "confidence": 0.90},
            {"step": 3, "evidence": "电容量增长3.5%表明绝缘结构变化", "confidence": 0.87},
            {"step": 4, "evidence": "末屏电流检测确认受潮", "confidence": 0.92},
        ],
        "corrective_actions": [
            "加强监测，每月测量介损和电容量",
            "安排更换A相高压套管",
            "新套管安装前进行介损和电容量检测",
            "更换后开展局放试验验证",
        ],
        "prevention_measures": [
            "建立套管在线监测（介损+电容量）",
            "检查套管末屏密封状况",
            "同厂家同型号套管开展普查",
        ],
        "resolution_date": "2024-06-30",
        "cost": 120000,
        "downtime_hours": 72,
    },
    {
        "case_id": "FC-005",
        "title": "220kV断路器操动机构故障",
        "equipment_type": "breaker",
        "equipment_id": "CB-001",
        "fault_type": "机械故障",
        "fault_subtype": "操动机构卡涩",
        "severity": "严重",
        "occurrence_date": "2024-02-18",
        "description": "220kV滨西线断路器在执行分闸操作时，分闸时间由正常45ms延长至78ms，超过标准限值。检查发现操动机构液压缸密封圈磨损导致液压油泄漏。",
        "symptoms": [
            "分闸时间78ms（标准≤60ms）",
            "分闸速度降低（由8.5m/s降至6.2m/s）",
            "液压机构油压保持能力下降",
            "机构箱底部发现油渍",
        ],
        "root_cause": "液压操动机构主缸密封圈磨损，导致液压油内泄，操动力不足",
        "evidence_chain": [
            {"step": 1, "evidence": "分闸时间78ms超标30%", "confidence": 0.99},
            {"step": 2, "evidence": "行程-时间曲线分析速度明显降低", "confidence": 0.96},
            {"step": 3, "evidence": "液压保压试验24h压降2.5MPa（标准≤0.5MPa）", "confidence": 0.95},
            {"step": 4, "evidence": "拆检发现主缸密封有明显磨损痕迹", "confidence": 1.0},
        ],
        "corrective_actions": [
            "更换液压缸全套密封件",
            "更换液压油并清洗油路",
            "进行机械特性试验确认合格",
            "进行200次操作循环老练试验",
        ],
        "prevention_measures": [
            "安装断路器机械特性在线监测",
            "缩短液压机构密封件更换周期（5年）",
            "同型号断路器开展操动特性普查",
        ],
        "resolution_date": "2024-03-05",
        "cost": 65000,
        "downtime_hours": 96,
    },
    {
        "case_id": "FC-006",
        "title": "500kV变压器铁芯多点接地",
        "equipment_type": "transformer",
        "equipment_id": "TR-005",
        "fault_type": "铁芯故障",
        "fault_subtype": "铁芯多点接地",
        "severity": "一般",
        "occurrence_date": "2025-01-05",
        "description": "500kV萧山变2号主变在线监测发现铁芯接地电流异常增大，从正常0.05A升至1.8A，判断为铁芯多点接地故障。",
        "symptoms": [
            "铁芯接地电流从0.05A升至1.8A",
            "油中H2含量轻微增长（12→25ppm）",
            "铁芯夹件接地电流同步增大",
        ],
        "root_cause": "铁芯底部沉积金属异物，在运行振动下形成第二接地点",
        "evidence_chain": [
            {"step": 1, "evidence": "铁芯接地电流持续大于1A", "confidence": 0.98},
            {"step": 2, "evidence": "外施交流电压法确认存在第二接地点", "confidence": 0.93},
            {"step": 3, "evidence": "油中H2轻微增长提示有微弱放电", "confidence": 0.80},
        ],
        "corrective_actions": [
            "加装限流电阻临时处理",
            "安排停电进行铁芯绝缘检测",
            "必要时进行吊罩检查清理异物",
        ],
        "prevention_measures": [
            "保持铁芯接地电流在线监测",
            "大修时彻底清理铁芯底部",
            "安装铁芯接地电流报警装置（>0.3A报警）",
        ],
        "resolution_date": None,
        "cost": None,
        "downtime_hours": None,
    },
]


def get_fault_case_by_equipment(equipment_id: str) -> list[dict]:
    """获取设备关联的故障案例"""
    return [fc for fc in FAULT_CASES if fc["equipment_id"] == equipment_id]


def get_fault_case_by_type(fault_type: str) -> list[dict]:
    """按故障类型查找案例"""
    return [fc for fc in FAULT_CASES if fc["fault_type"] == fault_type]
