/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentPipeline: typeof import('./components/ui/AgentPipeline.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppShell: typeof import('./components/ui/AppShell.vue')['default']
    HeaderBar: typeof import('./components/layout/HeaderBar.vue')['default']
    MetricCard: typeof import('./components/ui/MetricCard.vue')['default']
    RiskBadge: typeof import('./components/ui/RiskBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    StatCard: typeof import('./components/common/StatCard.vue')['default']
    StatusBadge: typeof import('./components/common/StatusBadge.vue')['default']
  }
}
